[tool.poetry]
name = "aifs"
version = "0.0.2"
description = "Local semantic search. Stupidly simple."
authors = ["Killian Lucas <killian@openinterpreter.com>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.9.0,<3.12"
unstructured = {extras = ["all-docs"], version = "^0.12.0"}
chromadb = "^0.4.22"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
